In [1]:
import numpy as np
import time

In [2]:
def validNumber(number, rowNumber, columnNumber):
    global sudoku
    if number in sudoku[rowNumber]:
        return 0
    if number in sudoku[:,columnNumber]:
        return 0
    for row in sudoku[rowNumber//3*3:(rowNumber+1)//3*3,columnNumber//3*3:(columnNumber+1)//3*3]:
        if number in row:
            return 0
    return 1

In [3]:
def solveSudoku():
    iterations = 0
    millis = time.time()
    count = 0
    while count < 81:
        i, j = count//9, count%9
        state = 1
        num = sudoku[i][j]
        while not sudokuState[i][j] and state:
            iterations+=1
            if num < 9:
                num += 1
            if (num < 10 and validNumber(num, i, j)):
                sudoku[i][j] = num
                state = 0
                count += 1
                i, j = count//9, count%9
                break
            elif num == 9 and not validNumber(num, i, j):
                sudoku[i][j] = 0
                count -= 1
                i, j = count//9, count%9
                while sudokuState [i][j]:
                    count -= 1
                    i, j = count//9, count%9
                break
        if count < 81 and sudokuState[i][j]:
            count += 1
            i, j = count//9, count%9

    print ('evaluation time in seconds:', time.time() - millis)
    print ("number of iterations :",iterations)
    print()
    for i in range(9):
        print(end="  ")
        for j in range(9):
            print (sudoku[i][j],end="|")
            if (j+1)%3 == 0:
                print (end="\b  ")
        if (i+1)%3:
            print("\n-----------------------")
        else:
            print("\n")


In [4]:
mat = input("enter numbers\n")
sudoku = []
for i in mat.split(" "):
    row = []
    for j in i:
        row.append(int(j))
    sudoku.append(row)

sudoku = np.array(sudoku)
print ('\n',sudoku)

sudokuState = []
for row in sudoku:
    state = []
    for element in row:
        if element == 0:
            state.append(0)
        else:
            state.append(1)
    sudokuState.append(state)
# print (np.array(sudokuState))

solveSudoku()

enter numbers
001600900 000001007 280040000 000080100 000300040 006007030 700900000 010000420 090005000

 [[0 0 1 6 0 0 9 0 0]
 [0 0 0 0 0 1 0 0 7]
 [2 8 0 0 4 0 0 0 0]
 [0 0 0 0 8 0 1 0 0]
 [0 0 0 3 0 0 0 4 0]
 [0 0 6 0 0 7 0 3 0]
 [7 0 0 9 0 0 0 0 0]
 [0 1 0 0 0 0 4 2 0]
 [0 9 0 0 0 5 0 0 0]]
evaluation time in seconds: 0.15021181106567383
number of iterations : 18327

  3|2|1  6|5|4  9|7|8  
-----------------------
  4|3|2  5|6|1  8|9|7  
-----------------------
  2|8|5  1|4|9  7|6|3  

  6|4|9  7|8|3  1|5|2  
-----------------------
  5|7|8  3|9|2  6|4|1  
-----------------------
  8|5|6  4|1|7  2|3|9  

  7|6|3  9|2|8  5|1|4  
-----------------------
  9|1|7  8|3|6  4|2|5  
-----------------------
  1|9|4  2|7|5  3|8|6  

